import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
// import ToastProvider from "./(components)/Toastify";
import { Toaster } from "react-hot-toast";
import Header from "@/components/header/Header";

const libre = Libre_Franklin({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className={libre.className}>
        <Header />
        <main>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
