import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";

import SessionProvider from "@/components/session/SessionProvider";
import { Toaster } from "react-hot-toast";
import Header from "@/components/header/Header";
import { getServerSession } from "next-auth";
import { NextAuthOptions } from "./api/auth/[...nextauth]/route";

const libre = Libre_Franklin({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(NextAuthOptions);
  return (
    <html lang="en" className="h-screen">
      <body className={libre.className}>
        <SessionProvider session={session}>
          <Header />
          <main>
            {children}
            <Toaster />
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
